In [1]:
import pandas as pd
import numpy as np

import datetime

import warnings
warnings.filterwarnings('ignore')

## --- ntcn -

In [2]:
df = pd.read_csv('test_kosm.csv', delimiter=';')
df

    otryad      fio  pnd   vt   sr  cht   pt   sb   vs
0        2   leonov  2.0  1.0  NaN  2.0  NaN  3.0  NaN
1        2  komarov  NaN  NaN  2.0  NaN  NaN  NaN  NaN
2        1  gagarin  1.0  NaN  NaN  NaN  NaN  NaN  2.0
3        1    titov  3.0  NaN  3.0  2.0  1.0  NaN  NaN
4        2   leonov  1.0  NaN  NaN  NaN  NaN  NaN  NaN
5        2  komarov  NaN  NaN  3.0  NaN  NaN  2.0  1.0
6        1  gagarin  2.0  NaN  NaN  NaN  2.0  NaN  NaN
7        1    titov  3.0  NaN  1.0  NaN  NaN  NaN  NaN
8        2   leonov  4.0  NaN  4.0  NaN  1.0  NaN  NaN
9        2  komarov  NaN  NaN  2.0  NaN  NaN  NaN  NaN
10       1  gagarin  5.0  NaN  NaN  1.0  NaN  1.0  NaN
11       1    titov  1.0  NaN  2.0  NaN  NaN  3.0  1.0

In [4]:
df_gr = df.groupby(['otryad', 'fio']).sum()
df_gr

                pnd   vt   sr  cht   pt   sb   vs
otryad fio
1      gagarin  8.0  0.0  0.0  1.0  2.0  1.0  2.0
       titov    7.0  0.0  6.0  2.0  1.0  3.0  1.0
2      komarov  0.0  0.0  7.0  0.0  0.0  2.0  1.0
       leonov   7.0  1.0  4.0  2.0  1.0  3.0  0.0

In [5]:
df_gr1 = df.groupby(['fio']).sum()
df_gr1

         otryad  pnd   vt   sr  cht   pt   sb   vs
fio
gagarin       3  8.0  0.0  0.0  1.0  2.0  1.0  2.0
komarov       6  0.0  0.0  7.0  0.0  0.0  2.0  1.0
leonov        6  7.0  1.0  4.0  2.0  1.0  3.0  0.0
titov         3  7.0  0.0  6.0  2.0  1.0  3.0  1.0

In [6]:
df_max_col = df_gr.max(axis=1)
df_max_col

otryad  fio
1       gagarin    8.0
        titov      7.0
2       komarov    7.0
        leonov     7.0
dtype: float64

In [480]:
# df_gr.loc[df_gr.index == 'komarov'].max(axis=1).max()

In [481]:
# for row in range(len(df_gr.index)):
#     df_gr.idxmax(axis=1)
#     print(f'Max element of row {df_gr.index[row]} is:', max(df_gr.iloc[row]))

In [7]:
df_col = df_gr.idxmax(axis=1)
df_col

otryad  fio
1       gagarin    pnd
        titov      pnd
2       komarov     sr
        leonov     pnd
dtype: object

In [8]:
df_result = pd.concat([df_col, df_max_col], axis=1)
df_result

                  0    1
otryad fio
1      gagarin  pnd  8.0
       titov    pnd  7.0
2      komarov   sr  7.0
       leonov   pnd  7.0

In [484]:
df_result.to_excel('111.xlsx')

## НОВЫЙ ТЕСТ

In [9]:
df_pik = pd.read_csv('тест_транспорт_пик_подг.csv', delimiter=';', encoding='cp1251')
df_pik.head(2)

,Наименование филиала,Необходимый тип транспортного средства,Подана заявка,Выполнена заявка
0,Отдел МТО,Легковой административный транспорт,01.08.2022,01.08.2022
1,ВПС Солнцево,Машина с носилками,01.08.2022,01.08.2022

In [10]:
df_pik = df_pik[['Наименование филиала ', 'Необходимый тип транспортного средства',
       'Подана заявка', 'Выполнена заявка']]

In [11]:
#  переименуем покороче столбцы
df_pik.rename(columns={'Наименование филиала ': 'филиал'}, inplace=True)
df_pik.rename(columns={'Необходимый тип транспортного средства': 'тип'}, inplace=True)
df_pik.rename(columns={'Подана заявка': 'Подана'}, inplace=True)
df_pik.rename(columns={'Выполнена заявка': 'Выполнена'}, inplace=True)

In [12]:
#  --------- DATATIME
df_pik['Выполнена'] = pd.to_datetime(df_pik['Выполнена'], dayfirst=True, errors = 'coerce').dt.normalize()
df_pik['Подана'] = pd.to_datetime(df_pik['Подана'], dayfirst=True, errors = 'coerce').dt.normalize()

In [13]:
df_pik['Подана'].max().to_pydatetime().date().strftime('%Y-%m-%d')

'2022-11-09'

In [119]:
%%time
# import time 
a = 1
# time.sleep(5)

CPU times: total: 0 ns
Wall time: 0 ns

In [124]:
# # ---- найдем мин и макс ----
# # dv_min = df_pik['Выполнена'].min().to_pydatetime().date().strftime('%Y-%m-%d')
# # dv_max = df_pik['Выполнена'].max().to_pydatetime().date().strftime('%Y-%m-%d')
# # dp_min = df_pik['Подана'].min().to_pydatetime().date().strftime('%Y-%m-%d')
# # dp_max = df_pik['Подана'].max().to_pydatetime().date().strftime('%Y-%m-%d')
# # ------------------------
dv_min = df_pik['Выполнена'].min().to_pydatetime().date()
dv_max = df_pik['Выполнена'].max().to_pydatetime().date()
dp_min = df_pik['Подана'].min().to_pydatetime().date()
dp_max = df_pik['Подана'].max().to_pydatetime().date()
# print(dv_min, dv_max, dp_min, dp_max)
date_list = [dv_min, dv_max, dp_min, dp_max]
start_date = min(date_list)
end_date = max(date_list)
print(start_date, end_date)

2022-08-01 2022-12-06

In [123]:
#  ------------- Временные СТАРТ и ЭНД ----------
# For capturing the execution time

# start_date = datetime.datetime.strptime('2022-08-01', "%Y-%m-%d").date()
# end_date = datetime.datetime.strptime('2022-09-10', "%Y-%m-%d").date()

In [107]:
# /////////////---------------------------------------------///////////////// cicl
# end_date = df_pik['Выполнена'].max().to_pydatetime().date()
# start_date = df_pik['Выполнена'].min().to_pydatetime().date()
# start_date = datetime.datetime.strptime('2022-08-01', "%Y-%m-%d").date()
# end_date = datetime.datetime.strptime('2022-08-05', "%Y-%m-%d").date()

# delta = datetime.timedelta(days=1)

# data_list = []
# while (start_date <= end_date):
#     print(start_date.strftime("%Y-%m-%d"), type(start_date.strftime("%B %d, %Y")), end="\n")
#     data_list.append(start_date.strftime("%Y-%m-%d"))
#     start_date += delta

# data_list

In [125]:
# -------------------------------- работает по формированию НУЛЕВЫХ колонок ---------
def create_df_col(df, start, end):
    start_date = start
    end_date = end 
    df = df
    delta = datetime.timedelta(days=1)
    # data_list = []
    while (start_date <= end_date):
        
        df[start_date.strftime("%Y-%m-%d")] = 0  # создаем строку в DF
        start_date += delta

In [126]:
create_df_col(df_pik, start_date, end_date)
df_pik

,филиал,тип,Подана,Выполнена,2022-08-01,2022-08-02,2022-08-03,2022-08-04,2022-08-05,2022-08-06,...,2022-11-27,2022-11-28,2022-11-29,2022-11-30,2022-12-01,2022-12-02,2022-12-03,2022-12-04,2022-12-05,2022-12-06
0,Отдел МТО,Легковой административный транспорт,2022-08-01,2022-08-01,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ВПС Солнцево,Машина с носилками,2022-08-01,2022-08-01,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,ВПС Хорошёво,Машина с носилками,2022-08-01,2022-08-02,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Администрация,Легковой административный транспорт,2022-08-01,2022-08-02,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ВПС Преображенское,Машина СМП/ЦЭМП (тяжелые пациенты с мед.сопров...,2022-08-01,2022-08-01,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2703,ВПС Куркино,Машина СМП/ЦЭМП (тяжелые пациенты с мед.сопров...,2022-11-09,2022-11-09,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2704,ВПС ПМХ,Машина с носилками,2022-11-09,2022-11-10,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2705,Савеловский (4 ОПМПВ),Машина с носилками,2022-11-09,2022-11-10,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2706,Зеленоград,Машина с носилками,2022-11-09,2022-11-10,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2707,Зеленоград,Машина с носилками,2022-11-09,2022-11-10,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [100]:
#  -------------------------------------------- Взять строку ---------------- df_pik.iloc [5]
#  -------------------------------------------- Взять имя столбца ------------ df_pik.keys()[4]
#  -------------------------------------------- Прогнать по циклц  -----
#  -------------------------------------------- Взять ячейку----------- ----- df_pik['2022-08-01'].values[1]
#  -------------------------------------------- Convert str to Date ----------pd.to_datetime(str(df_pik.keys()[4])).to_pydatetime().date()
#  -------------------------------------------- Convert Date to str  --------

In [127]:
# carrent_date = start_date 
# end_date = end_date

for i_stroka in range(df_pik['Подана'].shape[0]): #  --- stroki
  
    # --- сначение текущей строки ячейки   'Подана'       
    x = pd.to_datetime(str(df_pik['Подана'].values[i_stroka])).to_pydatetime().date()
    # --- сначение текущей строки ячейки   'Выполнена'       
    y = pd.to_datetime(str(df_pik['Выполнена'].values[i_stroka])).to_pydatetime().date()   
    
    for j_colonka in range(4,len(df_pik.columns)):

        # ----- приведем имя колонки к дате  
        (j_colonka)
        current_date = pd.to_datetime(str(df_pik.keys()[j_colonka])).to_pydatetime().date()
        
        if (x <= current_date and (y >= current_date)):
            df_pik[df_pik.keys()[j_colonka]].values[i_stroka] =  1

In [128]:
df_pik.head(5)

,филиал,тип,Подана,Выполнена,2022-08-01,2022-08-02,2022-08-03,2022-08-04,2022-08-05,2022-08-06,...,2022-11-27,2022-11-28,2022-11-29,2022-11-30,2022-12-01,2022-12-02,2022-12-03,2022-12-04,2022-12-05,2022-12-06
0,Отдел МТО,Легковой административный транспорт,2022-08-01,2022-08-01,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ВПС Солнцево,Машина с носилками,2022-08-01,2022-08-01,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,ВПС Хорошёво,Машина с носилками,2022-08-01,2022-08-02,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Администрация,Легковой административный транспорт,2022-08-01,2022-08-02,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ВПС Преображенское,Машина СМП/ЦЭМП (тяжелые пациенты с мед.сопров...,2022-08-01,2022-08-01,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [129]:
df_gr = df_pik.groupby(['тип']).sum()
df_gr

,2022-08-01,2022-08-02,2022-08-03,2022-08-04,2022-08-05,2022-08-06,2022-08-07,2022-08-08,2022-08-09,2022-08-10,...,2022-11-27,2022-11-28,2022-11-29,2022-11-30,2022-12-01,2022-12-02,2022-12-03,2022-12-04,2022-12-05,2022-12-06
тип,,,,,,,,,,,,,,,,,,,,,
Без машины,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Грузовой административный транспорт,0,0,0,6,5,4,4,10,9,8,...,0,0,0,0,0,0,0,0,0,0
Легковой административный транспорт,3,3,3,3,3,1,1,5,4,7,...,0,0,0,0,0,0,0,0,0,0
"Машина СМП/ЦЭМП (тяжелые пациенты с мед.сопровождением, респираторная поддержка )",2,1,1,3,3,2,1,2,2,1,...,0,0,0,0,0,0,0,0,0,0
Машина без носилок (ВПС),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Машина с носилками,10,29,45,47,39,29,22,39,39,41,...,1,1,1,1,1,1,1,1,1,1
Скорая помощь (Центр),1,2,1,2,5,1,2,5,2,5,...,0,0,0,0,0,0,0,0,0,0

In [78]:
for j_colonka in range(4,len(df_pik.columns)):

        # ----- приведем имя колонки к дате  
        # print(j_colonka)
        # current_date = pd.to_datetime(str(df_pik.keys()[j_colonka])).to_pydatetime().date()
    print(df_pik.keys()[j_colonka])

2022-08-01
2022-08-02
2022-08-03
2022-08-04
2022-08-05

In [29]:
(end_date - start_date)

datetime.timedelta(days=4)

In [495]:
#  -------------------------------------------- Пишем 1 в соотвт колонки дат -----

In [497]:
# delta = datetime.timedelta(days=1)
#     # data_list = []
# carrent_date = start_date
# while (carrent_date <= end_date):
#     # --- Текущая дата от мин до Макс ----- 
#     print(carrent_date.strftime("%Y-%m-%d"))
    
#     # ----- Вложенный цикл  проверки ---- 
#     if (podana <= carrent_date) and (vipolnena >= carrent_date):
#         df_pik[carrent_date]  = 1
#     start_date += delta

In [498]:
# def insert_1_in_data(df, start, end, podana, vipolnena):
    
#     df = df
#     carrent_date = start 
#     end_date = end
    
#     delta = datetime.timedelta(days=1)
#     # data_list = []
#     # carrent_date = start_date
#     while (carrent_date <= end_date):
#         # --- Текущая дата от мин до Макс ----- 
#         print(carrent_date.strftime("%Y-%m-%d"))

#         # ----- Вложенный цикл  проверки ---- 
#         if (podana <= carrent_date) and (podana <= carrent_date + delta) and (vipolnena >= carrent_date):
#         #     # df[carrent_date]  = 1
#         # df[carrent_date] = df.apply (lambda x:  1 if ((x['Подана'] <= carrent_date) and (x['Подана'] <= carrent_date + delta) and (x['Выполнена'] <= carrent_date)) else 0)
#             df[carrent_date]  = 1
            
#         carrent_date += delta

In [499]:
cols = df_pik.columns

for i in range(len(cols)): 
    print(cols[i])

филиал
тип
Подана
Выполнена
2022-08-01
2022-08-02
2022-08-03
2022-08-04
2022-08-05

In [500]:
# ------------строка ячейка даты ---------- дата

pd.to_datetime(str(df_pik['Подана'].values[110])).to_pydatetime().date()

datetime.date(2022, 8, 4)

In [501]:
df_pik['Подана'].shape[0]

2708

In [502]:
# df.apply (lambda x:  1 if ((x['Подана'] = ) and (x['Подана'] <= carrent_date + delta) and (x['Выполнена'] <= carrent_date)) else 0)

In [503]:
df = df_pik
carrent_date = start_date 
end_date = end_date

delta = datetime.timedelta(days=1)
carrent_date = start_date

while (carrent_date <= end_date):
    # --- Текущая дата от мин до Макс ----- 
    print(carrent_date.strftime("%Y-%m-%d"))
    for i in range(df_pik['Подана'].shape[0]):
        # --- сначение текущей строки ячейки   'Подана'       
        podana = pd.to_datetime(str(df_pik['Подана'].values[i])).to_pydatetime().date()
        
       
        # --- сначение текущей строки ячейки   'Выполнена'       
        vipolnena = pd.to_datetime(str(df_pik['Выполнена'].values[i])).to_pydatetime().date()
        
        # ----- Вложенный цикл  проверки ---- 
        # if (podana <= carrent_date) and (podana <= carrent_date + delta) and (vipolnena >= carrent_date):
        if (podana <= carrent_date) and (vipolnena >= carrent_date):
            df_pik[carrent_date].values[i] = 1

    carrent_date += delta

2022-08-01

KeyError: datetime.date(2022, 8, 1)

In [504]:
df_pik

,филиал,тип,Подана,Выполнена,2022-08-01,2022-08-02,2022-08-03,2022-08-04,2022-08-05
0,Отдел МТО,Легковой административный транспорт,2022-08-01,2022-08-01,0,0,0,0,0
1,ВПС Солнцево,Машина с носилками,2022-08-01,2022-08-01,0,0,0,0,0
2,ВПС Хорошёво,Машина с носилками,2022-08-01,2022-08-02,0,0,0,0,0
3,Администрация,Легковой административный транспорт,2022-08-01,2022-08-02,0,0,0,0,0
4,ВПС Преображенское,Машина СМП/ЦЭМП (тяжелые пациенты с мед.сопров...,2022-08-01,2022-08-01,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
2703,ВПС Куркино,Машина СМП/ЦЭМП (тяжелые пациенты с мед.сопров...,2022-11-09,2022-11-09,0,0,0,0,0
2704,ВПС ПМХ,Машина с носилками,2022-11-09,2022-11-10,0,0,0,0,0
2705,Савеловский (4 ОПМПВ),Машина с носилками,2022-11-09,2022-11-10,0,0,0,0,0
2706,Зеленоград,Машина с носилками,2022-11-09,2022-11-10,0,0,0,0,0
2707,Зеленоград,Машина с носилками,2022-11-09,2022-11-10,0,0,0,0,0

In [505]:
# for i in range(df_pik['Подана'].shape[0]):
        
#     print(i)
#         # df.apply (lambda x:  1 if ((x['Подана'] <= carrent_date) and (x['Подана'] <= carrent_date + delta) and (x['Выполнена'] <= carrent_date)) else 0)

In [506]:
# df_pik.apply(lambda x: insert_1_in_data(df_pik, start_date, end_date, x['Подана'],x['Выполнена']),axis=1)

# df['status'] = df['points'].apply ( lambda x: ' Bad ' if x < 20 else ' Good')

# df['col_3'] = df.apply(lambda x: f(x.col_1, x.col_2), axis=1)

In [507]:
df_pik

,филиал,тип,Подана,Выполнена,2022-08-01,2022-08-02,2022-08-03,2022-08-04,2022-08-05
0,Отдел МТО,Легковой административный транспорт,2022-08-01,2022-08-01,0,0,0,0,0
1,ВПС Солнцево,Машина с носилками,2022-08-01,2022-08-01,0,0,0,0,0
2,ВПС Хорошёво,Машина с носилками,2022-08-01,2022-08-02,0,0,0,0,0
3,Администрация,Легковой административный транспорт,2022-08-01,2022-08-02,0,0,0,0,0
4,ВПС Преображенское,Машина СМП/ЦЭМП (тяжелые пациенты с мед.сопров...,2022-08-01,2022-08-01,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
2703,ВПС Куркино,Машина СМП/ЦЭМП (тяжелые пациенты с мед.сопров...,2022-11-09,2022-11-09,0,0,0,0,0
2704,ВПС ПМХ,Машина с носилками,2022-11-09,2022-11-10,0,0,0,0,0
2705,Савеловский (4 ОПМПВ),Машина с носилками,2022-11-09,2022-11-10,0,0,0,0,0
2706,Зеленоград,Машина с носилками,2022-11-09,2022-11-10,0,0,0,0,0
2707,Зеленоград,Машина с носилками,2022-11-09,2022-11-10,0,0,0,0,0

In [508]:
df_gr = df_pik.groupby('тип').sum()
df_gr

,2022-08-01,2022-08-02,2022-08-03,2022-08-04,2022-08-05
тип,,,,,
Без машины,0,0,0,0,0
Грузовой административный транспорт,0,0,0,0,0
Легковой административный транспорт,0,0,0,0,0
"Машина СМП/ЦЭМП (тяжелые пациенты с мед.сопровождением, респираторная поддержка )",0,0,0,0,0
Машина без носилок (ВПС),0,0,0,0,0
Машина с носилками,0,0,0,0,0
Скорая помощь (Центр),0,0,0,0,0

## СуперНОВЫЙ ТЕСТ

In [531]:
df_pik = pd.read_csv('тест_транспорт_пик_подг.csv', delimiter=';', encoding='cp1251')
df_pik.head(2)

,Наименование филиала,Необходимый тип транспортного средства,Подана заявка,Выполнена заявка
0,Отдел МТО,Легковой административный транспорт,01.08.2022,01.08.2022
1,ВПС Солнцево,Машина с носилками,01.08.2022,01.08.2022

In [532]:
df_pik = df_pik[['Наименование филиала ', 'Необходимый тип транспортного средства',
       'Подана заявка', 'Выполнена заявка']]

In [589]:
#  переименуем покороче столбцы
df_pik.rename(columns={'Наименование филиала ': 'филиал'}, inplace=True)
df_pik.rename(columns={'Необходимый тип транспортного средства': 'тип'}, inplace=True)
df_pik.rename(columns={'Подана заявка': 'Подана'}, inplace=True)
df_pik.rename(columns={'Выполнена заявка': 'Выполнена'}, inplace=True)

In [590]:
#  --------- DATATIME
df_pik['Выполнена'] = pd.to_datetime(df_pik['Выполнена'], dayfirst=True, errors = 'coerce').dt.normalize()
df_pik['Подана'] = pd.to_datetime(df_pik['Подана'], dayfirst=True, errors = 'coerce').dt.normalize()

In [591]:
df = df_pik

In [592]:
#  ------------- Временные СТАРТ и ЭНД ----------
# start_date = datetime.datetime.strptime('2022-08-01', "%Y-%m-%d").date()
# end_date = datetime.datetime.strptime('2022-08-05', "%Y-%m-%d").date()

In [593]:
dv_min = df['Выполнена'].min().to_pydatetime().date()
dv_max = df['Выполнена'].max().to_pydatetime().date()
dp_min = df['Подана'].min().to_pydatetime().date()
dp_max = df['Подана'].max().to_pydatetime().date()
# print(dv_min, dv_max, dp_min, dp_max)
date_list = [dv_min, dv_max, dp_min, dp_max]
start_date = min(date_list)
end_date = max(date_list)
print(start_date, end_date)

2022-08-01 2022-12-06

datetime.date(2022, 12, 6)

In [594]:
carrent_date = start_date 
end_date = end_date
delta = datetime.timedelta(days=1)
dict_date = {}                     # ---- dict  по всем датам, встречающимся в df ----
carrent_date = start_date

while (carrent_date <= end_date):
    # --- Текущая дата от мин до Макс ----- 
    print(carrent_date,  type(carrent_date))
    # dict_date
    dict_date[carrent_date] = 0  # -----------------закинули 0 в словарь дат ---
    carrent_date += delta

2022-08-01 <class 'datetime.date'>
2022-08-02 <class 'datetime.date'>
2022-08-03 <class 'datetime.date'>
2022-08-04 <class 'datetime.date'>
2022-08-05 <class 'datetime.date'>
2022-08-06 <class 'datetime.date'>
2022-08-07 <class 'datetime.date'>
2022-08-08 <class 'datetime.date'>
2022-08-09 <class 'datetime.date'>
2022-08-10 <class 'datetime.date'>
2022-08-11 <class 'datetime.date'>
2022-08-12 <class 'datetime.date'>
2022-08-13 <class 'datetime.date'>
2022-08-14 <class 'datetime.date'>
2022-08-15 <class 'datetime.date'>
2022-08-16 <class 'datetime.date'>
2022-08-17 <class 'datetime.date'>
2022-08-18 <class 'datetime.date'>
2022-08-19 <class 'datetime.date'>
2022-08-20 <class 'datetime.date'>
2022-08-21 <class 'datetime.date'>
2022-08-22 <class 'datetime.date'>
2022-08-23 <class 'datetime.date'>
2022-08-24 <class 'datetime.date'>
2022-08-25 <class 'datetime.date'>
2022-08-26 <class 'datetime.date'>
2022-08-27 <class 'datetime.date'>
2022-08-28 <class 'datetime.date'>
2022-08-29 <class 'datetime.date'>
2022-08-30 <class 'datetime.date'>
2022-08-31 <class 'datetime.date'>
2022-09-01 <class 'datetime.date'>
2022-09-02 <class 'datetime.date'>
2022-09-03 <class 'datetime.date'>
2022-09-04 <class 'datetime.date'>
2022-09-05 <class 'datetime.date'>
2022-09-06 <class 'datetime.date'>
2022-09-07 <class 'datetime.date'>
2022-09-08 <class 'datetime.date'>
2022-09-09 <class 'datetime.date'>
2022-09-10 <class 'datetime.date'>
2022-09-11 <class 'datetime.date'>
2022-09-12 <class 'datetime.date'>
2022-09-13 <class 'datetime.date'>
2022-09-14 <class 'datetime.date'>
2022-09-15 <class 'datetime.date'>
2022-09-16 <class 'datetime.date'>
2022-09-17 <class 'datetime.date'>
2022-09-18 <class 'datetime.date'>
2022-09-19 <class 'datetime.date'>
2022-09-20 <class 'datetime.date'>
2022-09-21 <class 'datetime.date'>
2022-09-22 <class 'datetime.date'>
2022-09-23 <class 'datetime.date'>
2022-09-24 <class 'datetime.date'>
2022-09-25 <class 'datetime.date'>
2022-09-26 <class 'datetime.date'>
2022-09-27 <class 'datetime.date'>
2022-09-28 <class 'datetime.date'>
2022-09-29 <class 'datetime.date'>
2022-09-30 <class 'datetime.date'>
2022-10-01 <class 'datetime.date'>
2022-10-02 <class 'datetime.date'>
2022-10-03 <class 'datetime.date'>
2022-10-04 <class 'datetime.date'>
2022-10-05 <class 'datetime.date'>
2022-10-06 <class 'datetime.date'>
2022-10-07 <class 'datetime.date'>
2022-10-08 <class 'datetime.date'>
2022-10-09 <class 'datetime.date'>
2022-10-10 <class 'datetime.date'>
2022-10-11 <class 'datetime.date'>
2022-10-12 <class 'datetime.date'>
2022-10-13 <class 'datetime.date'>
2022-10-14 <class 'datetime.date'>
2022-10-15 <class 'datetime.date'>
2022-10-16 <class 'datetime.date'>
2022-10-17 <class 'datetime.date'>
2022-10-18 <class 'datetime.date'>
2022-10-19 <class 'datetime.date'>
2022-10-20 <class 'datetime.date'>
2022-10-21 <class 'datetime.date'>
2022-10-22 <class 'datetime.date'>
2022-10-23 <class 'datetime.date'>
2022-10-24 <class 'datetime.date'>
2022-10-25 <class 'datetime.date'>
2022-10-26 <class 'datetime.date'>
2022-10-27 <class 'datetime.date'>
2022-10-28 <class 'datetime.date'>
2022-10-29 <class 'datetime.date'>
2022-10-30 <class 'datetime.date'>
2022-10-31 <class 'datetime.date'>
2022-11-01 <class 'datetime.date'>
2022-11-02 <class 'datetime.date'>
2022-11-03 <class 'datetime.date'>
2022-11-04 <class 'datetime.date'>
2022-11-05 <class 'datetime.date'>
2022-11-06 <class 'datetime.date'>
2022-11-07 <class 'datetime.date'>
2022-11-08 <class 'datetime.date'>
2022-11-09 <class 'datetime.date'>
2022-11-10 <class 'datetime.date'>
2022-11-11 <class 'datetime.date'>
2022-11-12 <class 'datetime.date'>
2022-11-13 <class 'datetime.date'>
2022-11-14 <class 'datetime.date'>
2022-11-15 <class 'datetime.date'>
2022-11-16 <class 'datetime.date'>
2022-11-17 <class 'datetime.date'>
2022-11-18 <class 'datetime.date'>
2022-11-19 <class 'datetime.date'>
2022-11-20 <class 'datetime.date'>
2022-11-21 <class 'datetime.date'>
2022-11-22 <class 'datetime.date'>
2022-11-23 <class 'datetime.date'>
2022-11-24 <class 'datetime.date'>
2022-11-25 <class 'datetime.date'>
2022-11-26 <class 'datetime.date'>
2022-11-27 <class 'datetime.date'>
2022-11-28 <class 'datetime.date'>
2022-11-29 <class 'datetime.date'>
2022-11-30 <class 'datetime.date'>
2022-12-01 <class 'datetime.date'>
2022-12-02 <class 'datetime.date'>
2022-12-03 <class 'datetime.date'>
2022-12-04 <class 'datetime.date'>
2022-12-05 <class 'datetime.date'>
2022-12-06 <class 'datetime.date'>

In [584]:
# dict_date[datetime.date(2022, 8, 1)] = dict_date[datetime.date(2022, 8, 1)] + 1
# dict_date[datetime.date(2022, 8, 1)]

In [613]:
dff = dict_date
dff = pd.DataFrame(dff.items())

In [614]:
# dff = dff.rename(columns={0: 'Подана', 1: 'Было_в_день'})
# dff.columns
dff.columns.values[0] = "Подана"
dff.columns.values[1] = "Выполнена"
dff

ValueError: invalid literal for int() with base 10: 'Подана'

In [595]:
carrent_date = start_date 
end_date = end_date
while (carrent_date < end_date):
    # --- Текущая дата от мин до Макс ----- 
    # print(carrent_date,  type(carrent_date))
    for i in range(df['Подана'].shape[0]):
                # --- сначение текущей строки ячейки   'Подана'       
        x = pd.to_datetime(str(df['Подана'].values[i])).to_pydatetime().date()
   
        # --- сначение текущей строки ячейки   'Выполнена'       
        y = pd.to_datetime(str(df['Выполнена'].values[i])).to_pydatetime().date()
        # if (x <= carrent_date) and (y >= carrent_date):
        if (x <= carrent_date) and (y >= carrent_date):
            dict_date[carrent_date] = dict_date[carrent_date] + 1

    carrent_date += delta

In [596]:
dict_date

{datetime.date(2022, 8, 1): 16,
 datetime.date(2022, 8, 2): 35,
 datetime.date(2022, 8, 3): 50,
 datetime.date(2022, 8, 4): 61,
 datetime.date(2022, 8, 5): 55,
 datetime.date(2022, 8, 6): 37,
 datetime.date(2022, 8, 7): 30,
 datetime.date(2022, 8, 8): 61,
 datetime.date(2022, 8, 9): 56,
 datetime.date(2022, 8, 10): 62,
 datetime.date(2022, 8, 11): 51,
 datetime.date(2022, 8, 12): 55,
 datetime.date(2022, 8, 13): 37,
 datetime.date(2022, 8, 14): 39,
 datetime.date(2022, 8, 15): 45,
 datetime.date(2022, 8, 16): 48,
 datetime.date(2022, 8, 17): 50,
 datetime.date(2022, 8, 18): 49,
 datetime.date(2022, 8, 19): 50,
 datetime.date(2022, 8, 20): 40,
 datetime.date(2022, 8, 21): 30,
 datetime.date(2022, 8, 22): 56,
 datetime.date(2022, 8, 23): 51,
 datetime.date(2022, 8, 24): 46,
 datetime.date(2022, 8, 25): 48,
 datetime.date(2022, 8, 26): 52,
 datetime.date(2022, 8, 27): 39,
 datetime.date(2022, 8, 28): 37,
 datetime.date(2022, 8, 29): 49,
 datetime.date(2022, 8, 30): 63,
 datetime.date(2022, 8, 31): 66,
 datetime.date(2022, 9, 1): 64,
 datetime.date(2022, 9, 2): 48,
 datetime.date(2022, 9, 3): 32,
 datetime.date(2022, 9, 4): 23,
 datetime.date(2022, 9, 5): 58,
 datetime.date(2022, 9, 6): 65,
 datetime.date(2022, 9, 7): 57,
 datetime.date(2022, 9, 8): 57,
 datetime.date(2022, 9, 9): 46,
 datetime.date(2022, 9, 10): 27,
 datetime.date(2022, 9, 11): 31,
 datetime.date(2022, 9, 12): 49,
 datetime.date(2022, 9, 13): 53,
 datetime.date(2022, 9, 14): 55,
 datetime.date(2022, 9, 15): 48,
 datetime.date(2022, 9, 16): 49,
 datetime.date(2022, 9, 17): 38,
 datetime.date(2022, 9, 18): 38,
 datetime.date(2022, 9, 19): 53,
 datetime.date(2022, 9, 20): 54,
 datetime.date(2022, 9, 21): 53,
 datetime.date(2022, 9, 22): 48,
 datetime.date(2022, 9, 23): 52,
 datetime.date(2022, 9, 24): 35,
 datetime.date(2022, 9, 25): 36,
 datetime.date(2022, 9, 26): 41,
 datetime.date(2022, 9, 27): 50,
 datetime.date(2022, 9, 28): 58,
 datetime.date(2022, 9, 29): 52,
 datetime.date(2022, 9, 30): 57,
 datetime.date(2022, 10, 1): 38,
 datetime.date(2022, 10, 2): 31,
 datetime.date(2022, 10, 3): 53,
 datetime.date(2022, 10, 4): 49,
 datetime.date(2022, 10, 5): 61,
 datetime.date(2022, 10, 6): 52,
 datetime.date(2022, 10, 7): 59,
 datetime.date(2022, 10, 8): 44,
 datetime.date(2022, 10, 9): 31,
 datetime.date(2022, 10, 10): 49,
 datetime.date(2022, 10, 11): 53,
 datetime.date(2022, 10, 12): 48,
 datetime.date(2022, 10, 13): 59,
 datetime.date(2022, 10, 14): 59,
 datetime.date(2022, 10, 15): 36,
 datetime.date(2022, 10, 16): 32,
 datetime.date(2022, 10, 17): 51,
 datetime.date(2022, 10, 18): 59,
 datetime.date(2022, 10, 19): 52,
 datetime.date(2022, 10, 20): 47,
 datetime.date(2022, 10, 21): 48,
 datetime.date(2022, 10, 22): 32,
 datetime.date(2022, 10, 23): 27,
 datetime.date(2022, 10, 24): 47,
 datetime.date(2022, 10, 25): 52,
 datetime.date(2022, 10, 26): 52,
 datetime.date(2022, 10, 27): 49,
 datetime.date(2022, 10, 28): 42,
 datetime.date(2022, 10, 29): 28,
 datetime.date(2022, 10, 30): 26,
 datetime.date(2022, 10, 31): 45,
 datetime.date(2022, 11, 1): 58,
 datetime.date(2022, 11, 2): 60,
 datetime.date(2022, 11, 3): 47,
 datetime.date(2022, 11, 4): 23,
 datetime.date(2022, 11, 5): 32,
 datetime.date(2022, 11, 6): 27,
 datetime.date(2022, 11, 7): 43,
 datetime.date(2022, 11, 8): 47,
 datetime.date(2022, 11, 9): 49,
 datetime.date(2022, 11, 10): 21,
 datetime.date(2022, 11, 11): 4,
 datetime.date(2022, 11, 12): 1,
 datetime.date(2022, 11, 13): 1,
 datetime.date(2022, 11, 14): 1,
 datetime.date(2022, 11, 15): 1,
 datetime.date(2022, 11, 16): 1,
 datetime.date(2022, 11, 17): 1,
 datetime.date(2022, 11, 18): 1,
 datetime.date(2022, 11, 19): 1,
 datetime.date(2022, 11, 20): 1,
 datetime.date(2022, 11, 21): 1,
 datetime.date(2022, 11, 22): 1,
 datetime.date(2022, 11, 23): 1,
 datetime.date(2022, 11, 24): 1,
 datetime.date(2022, 11, 25): 1,
 datetime.date(2022, 11, 26): 1,
 datetime.date(2022, 11, 27): 1,
 datetime.date(2022, 11, 28): 1,
 datetime.date(2022, 11, 29): 1,
 datetime.date(2022, 11, 30): 1,
 datetime.date(2022, 12, 1): 1,
 datetime.date(2022, 12, 2): 1,
 datetime.date(2022, 12, 3): 1,
 datetime.date(2022, 12, 4): 1,
 datetime.date(2022, 12, 5): 1,
 datetime.date(2022, 12, 6): 0}

In [ ]:
[create] <=@needdate
  AND [create]< DATEADD(DAY,1,@needdate)
  AND [close] >= @needdate